#!/bin/bash
# Script to consolidate the Betty style checker into one script!
#
# Drop this script into your $PATH and set proper execute permissions.
#
# If you don't have Betty installed, this script will download it for you
# and run the installer. To run the installer, it needs root, so use sudo
# the first time you run it if you don't have it installed!

exists () {
    type "$1" > /dev/null 2>&1;
}

if ! exists betty-style 2>/dev/null ; then
    if [ "$(id -u)" != "0" ] ;
    then
	echo "Betty-style not found. Re-run as root to install!"
	exit 1
    fi
    cd /tmp/;git clone https://github.com/holbertonschool/Betty.git;cd Betty;./install.sh
    rm -rf /tmp/Betty/
    if exists betty-style 2>/dev/null ; then
	echo "Betty installed successfully! Re-run again normally without sudo."
	exit 0
    else
	echo "Error installing Betty! Try again or install manually."
    fi
fi

if [ "$#" = "0" ]; then
    echo "No arguments given to Betty."
    exit 1
fi

echo -e "Style:\n-----"
betty-style "$@"
echo -e "\nDocs:\n-----"
betty-doc "$@"
